services:
  customer-api:
    container_name: customer-api
    build:
      context: .
      target: ${ENV}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - migrate
    env_file:
      - .env
    volumes:
      - .:/app
  migrate:
    container_name: migrate
    build: .
    command: ["migrate", "-path", "./migrations", "-database", "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSL}", "up"] 
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:8
    command: redis-server --requirepass redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  pgdata:
  redis-data: